## Linear regression

In [1]:
import torch

In [2]:
# woring with Boston dataset for sklearn
from sklearn.datasets import load_boston

data = load_boston()

In [3]:
print(data.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [3]:
trainX = data.data
trainY = data.target

In [4]:
print('X shape ' + str(trainX.shape))
print('Y shape ' + str(trainY.shape))

X shape (506, 13)
Y shape (506,)


In [5]:
tenX = torch.tensor(trainX)
tenY = torch.tensor(trainY)

In [6]:
# normalize
std = tenX.std()
tenX -=tenX.mean()
tenX /= std

In [19]:
torch.eye(tenX.shape[1]).long()

tensor([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [21]:
theta_ML =  torch.matmul(torch.inverse(torch.matmul(tenX.t(),tenX) + torch.eye(tenX.shape[1]).double()), torch.matmul(tenX.t(),tenY))

In [28]:
y_pred = torch.matmul(tenX, theta_ML)

In [51]:
def MSE(y, y_pred):
    return torch.matmul((y - y_pred).view(-1,1).t(), (y - y_pred).view(-1,1)).mean() 

In [57]:
MSE(tenY,y_pred)

tensor(12228.0463, dtype=torch.float64)

In [30]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

In [31]:
lr.fit(trainX,trainY)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [32]:
sky_pred = lr.predict(trainX)

In [50]:
def MSE_sk(y, y_pred):
    return ((y - y_pred).T @ (y - y_pred)).mean()

In [58]:
MSE_sk(trainY, sky_pred)

11078.784577954977

In [48]:
type(trainX[0,0])

numpy.float64

In [56]:
MSE_sk(sky_pred, y_pred.numpy())

1149.2616830890233

## Define classes

In [46]:
from sklearn.linear_model import LinearRegression

In [3]:
from sklearn import linear_model

In [22]:
import torch
from torch import matmul, inverse

class LinearRegression:
    def __init__(self, fit_intercept=True, normalize=False, copy_X=True,
                 n_jobs=None, penality = 'l2', l = 0.1):
        self.fit_intercept = fit_intercept
        self.normalize = normalize
        self.copy_X = copy_X
        self.penality = penality
        self.l = l
        self.theta = None
        self.X = None
        self.y = None
        self.fitted = False
  
        
    def predict(self,X):
        if not self.fitted:
            print('Need to fit the model fisrt use model.fit')
            pass
        else:
            return matmul(X, self.theta)
    
    def fit(self, X,y):
        self.X = X
        self.y = y
        
        if self.copy_X:
            self.X = X.clone()
            
        if self.normalize:
            # normalize
            std = self.X.std()
            self.X -=self.X.mean()
            self.X /= std
        if self.penality == 'l2':
            self.theta =  matmul(inverse(matmul(self.X.t(),self.X) + self.l*torch.eye(self.X.shape[1]).double()), matmul(self.X.t(),self.y))
            self.fitted = True
        
    def get_report(self,X,y):
        y_perd = self.predict(X)
        mse = self.MSE(y, y_perd)
        pass
        
    def MSE(self, y, y_pred):
        return matmul((y - y_pred).view(-1,1).t(), (y - y_pred).view(-1,1)).mean() 


In [23]:
lin = LinearRegression()

In [24]:
lin.fit

<bound method LinearRegression.fit of <__main__.LinearRegression object at 0x7f6bafafa898>>

In [27]:
lin.predict(tenX).shape

torch.Size([506])

In [26]:
lin.fit(tenX, tenY)

## Non linear Transformation

In [28]:
import LinearRegression

In [30]:
lr = LinearRegression.LinearRegression()

In [90]:
def point_feature(x,k):
    feature = []
    for i in range(k+1):
        feature.append(x**i)
    return np.array(feature)

def poly_features(X, K):
    
    #X: inputs of size N x 1
    #K: degree of the polynomial
    # computes the feature matrix Phi (N x (K+1))
    
    N, D = X.shape
    
    #initialize Phi
    Phi = np.zeros((N, (K+1)*D))
    
    # Compute the feature matrix in stages
    Phi = np.apply_along_axis(point_feature,0,X, K).T 
    return np.reshape(Phi, (N,-1))

In [145]:
def trig_point_feature(x,k):
    feature = []
    feature.append(1)
    for i in range(1,k+1):
        feature.append(np.sin(2*np.pi*i*x))
        feature.append(np.cos(2*np.pi*i*x))
    return np.array(feature, dtype=float)

def trigonometric_features(X, K):
    
    #X: inputs of size N x 1
    #K: degree of the polynomial
    # computes the feature matrix Phi (N x (K+1))
    
    N, D = X.shape
    X = X.flatten()
    
    #initialize Phi
    Phi = np.zeros((D*N, (2*K+1)))
    
    # Compute the feature matrix in stages
    #Phi = np.apply_along_axis(trig_point_feature,0,X, K).T # np.zeros((N, K+1))
    for i in range(N):
        Phi[i,:] = trig_point_feature(X[i],K)
    return np.reshape(Phi, (N,-1))

In [147]:
def gaussian_feature(x, l, k, mu_range = (0,1)):
    feature = []
    feature.append(1)
    mu = 0
    mu_step = (mu_range[1] - mu_range[0])/k
    for i in range(1,k+1):
        mu = i * mu_step
        phi = np.exp(-((x - mu)**2)/(2*(l**2)))
        feature.append(phi)
    return np.array(feature)

def gaussian_features(X, K,l, mu_range = (0,1)):
    
    #X: inputs of size N x 1
    #K: degree of the polynomial
    # computes the feature matrix Phi (N x (K+1))
    
    N, D = X.shape
    X = X.flatten()
    
    #initialize Phi
    Phi = np.zeros((D*N, K+1))
    
    # Compute the feature matrix in stages
    #Phi = np.apply_along_axis(point_feature,0,X, K).T # np.zeros((N, K+1)) ## <-- EDIT THIS LINE
    for i in range(N):
        Phi[i,:] = gaussian_feature(X[i], l, K, mu_range)
    return np.reshape(Phi, (N,-1))

In [160]:
del(gaussian_features)

In [7]:
import torch
from torch import matmul, inverse
from LinearRegression import LinearRegression
import numpy as np
from Transformation import * 


class NonLinearRegression:
    def __init__(self, fit_intercept=True, normalize=False, copy_X=True,
                 n_jobs=None, penality = 'l2', l = 0.1, transformer = 'poly', K = 3, length = 0.1, mu_range = (0,1)):
        self.fit_intercept = fit_intercept
        self.normalize = normalize
        self.copy_X = copy_X
        self.n_jobs = n_jobs
        self.penality = penality
        self.l = l
        self.transformer = transformer
        self.K = K
        self.length = length
        self.mu_range = mu_range
        self.theta = None
        self.X = None
        self.y = None
        self.fitted = False
        
        self.lr = LinearRegression(self.fit_intercept, self.normalize, self.copy_X, self.n_jobs, self.penality, self.l)
  
        
    def predict(self,X):
        if not self.lr.fitted:
            print('Need to fit the model fisrt use model.fit')
            pass
        else:
            if self.transformer == 'poly':
                transformed_X = torch.from_numpy(poly_features(X, self.K))
            
            elif self.transformer == 'trigonometric':
                transformed_X = torch.from_numpy(trigonometric_features(X, self.K))
            
            elif self.transformer == 'gaussian':
                transformed_X = torch.from_numpy(gaussian_features(X, self.K, self.length, self.mu_range))
            
            else:
                print('Undefined transformations use poly, trigonometric or gaussian')
                pass
        
            return self.lr.predict(transformed_X)
    
    def fit(self, X,y):
        self.X = X
        self.y = y
        
        if self.transformer == 'poly':
            print(self.K)
            trans_X = torch.from_numpy(poly_features(self.X, self.K))
            
        elif self.transformer == 'trigonometric':
            trans_X = torch.from_numpy(trigonometric_features(self.X, self.K))
            
        elif self.transformer == 'gaussian':
            trans_X = torch.from_numpy(gaussian_features(self.X, self.K, self.length, self.mu_range))
        
        elif callable(self.transformer):
            trans_X = torch.from_numpy(self.transformer(self.X, self.K, self.length, self.mu_range))
        
        else:
            print('Undefined transformations use poly, trigonometric, gaussian or a user defined function')
            pass
        
        self.lr.fit(trans_X, self.y)
        self.theta = lr.theta #matmul(inverse(matmul(trans_X.t(),trans_X) + self.l*torch.eye(trans_X.shape[1]).double()), matmul(trans_X.t(),self.y)) #
        self.fitted = True
        
    def get_report(self,X,y):
        y_perd = self.predict(X)
        mse = self.MSE(y, y_perd)
        pass
        
    def MSE(self, y, y_pred):
        return matmul((y - y_pred).view(-1,1).t(), (y - y_pred).view(-1,1)).mean() 


In [14]:
lr = NonLinearRegression(K=5, transformer='gaussian')

In [15]:
lr.fit(tenX, tenY)

In [16]:
lr.predict(tenX).shape

torch.Size([506])

In [146]:
trigonometric_features(torch.tensor([1,2,3]).view(1,-1),2).shape

(1, 15)

In [123]:
print(trigonometric_features(torch.tensor([1]),2))
print(trigonometric_features(torch.tensor([2]),2))

[[ 1.         -0.2794155   0.96017029 -0.53657292  0.84385396]]
[[ 1.         -0.53657292  0.84385396 -0.90557836  0.42417901]]


In [18]:
callable(trig_point_feature)

True